apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: flask-app

build:
  artifacts:
    - image: europe-central2-docker.pkg.dev/skillsoft-1744084570602/sampleimage/flask-app

manifests:
  rawYaml:
    - deployment.yaml
    - service.yaml

deploy:
  kubectl: {}
